export const DOCUMENTATION_MARKDOWN = [
  "",
  "Welcome to the PingMyDB documentation. Our platform is designed to provide seamless, high-performance database monitoring for modern cloud infrastructure.",
  "",
  "Whether you're looking to eliminate cold starts or ensure 24/7 reliability, this guide will walk you through everything you need to know.",
  "",
  "---",
  "",
  "## 1. Overview",
  "",
  "**What is PingMyDB?**",
  "",
  "PingMyDB is a specialized database monitoring utility built specifically for cloud-hosted database instances. It acts as a lightweight, reliable heartbeat for your data infrastructure.",
  "",
  "Our primary goal is to prevent the common \"cold start\" problem where database providers pause inactive instances to save compute resources.",
  "",
  "**The Multi-Provider Solution**",
  "",
  "Many modern serverless database providers (like Supabase, Neon, and MongoDB Atlas) pause inactive instances after a period of idleness.",
  "",
  "This leads to significant latency spikes—often 2 to 10 seconds—when the next query arrives. PingMyDB keeps these instances \"warm\" by simulating regular, lightweight activity.",
  "",
  "**Supported Protocols**",
  "",
  "We currently provide native support for PostgreSQL, MongoDB, and MySQL. We are constantly expanding our compatibility based on community requirements.",
  "",
  "| Feature | Description |",
  "| :--- | :--- |",
  "| **DB Warmth** | Prevents instances from entering deep sleep |",
  "| **Latency Tracking** | Real-time monitoring of connection speed |",
  "| **Public Status Pages** | Share infrastructure health with stakeholders |",
  "| **Global Alerts** | Instant notifications via Email, Slack & Discord |",
  "",
  "---",
  "",
  "## 2. Technical Architecture",
  "",
  "PingMyDB is built on a distributed worker architecture designed for high availability and minimal footprint.",
  "",
  "**The Monitoring Pulse**",
  "",
  "When you add a monitor, our scheduling engine creates a recurring task using BullMQ and Redis. At the specified interval, a worker is dynamically assigned to perform a \"pulse\".",
  "",
  "A pulse consists of a secure connection handshake followed by a primitive query (e.g., `SELECT 1`). This activity is sufficient to signal to your provider that the instance is in use.",
  "",
  "**Stateless Efficiency**",
  "",
  "Unlike traditional monitoring tools, we do not maintain long-lived connection pools. Every connection is opened, queried, and closed immediately.",
  "",
  "This ensures that we never exhaust your database's connection limits or interfere with your application's own traffic.",
  "",
  "---",
  "",
  "## 3. Databases & Providers",
  "",
  "We optimize our monitoring logic for each specific protocol to ensure the most reliable heartbeat possible.",
  "",
  "### PostgreSQL",
  "",
  "Ideal for **Supabase**, **Neon**, and **Railway**. We use the standard wire protocol and support all common SSL modes. For Supabase users, this is the most effective way to prevent the 7-day auto-pause on free tiers.",
  "",
  "### MongoDB",
  "",
  "Optimized for **MongoDB Atlas**. Our workers utilize the standard `SRV` connection strings and perform a specialized admin-level ping that ignores your application collections.",
  "",
  "### MySQL",
  "",
  "Perfect for **Aiven**, **PlanetScale**, and **DigitalOcean**. We ensure that the connection handshake is completed successfully and the engine stays responsive.",
  "",
  "---",
  "",
  "## 4. Public Status Pages",
  "",
  "Transparency builds trust. PingMyDB allows you to generate high-fidelity, live status pages for your organization.",
  "",
  "**Setup & Customization**",
  "",
  "- **Custom Slugs**: Choose a unique URL (e.g., `pingmydb.com/status/acme-corp`).",
  "- **Visibility Control**: Toggle your page between `Public` (anyone with the link) and `Private` (locked).",
  "- **Live Metrics**: Public pages auto-refresh every 30 seconds to show real-time health and average latency.",
  "",
  "**What is shown?**",
  "",
  "Public pages only display your **unpaused** monitors. They hide all sensitive URIs and connection details, showing only the monitor name, current status (Operational/Degraded), and recent latency trends.",
  "",
  "---",
  "",
  "## 5. Alerts & Notifications",
  "",
  "Don't wait for a customer to tell you the site is down. Get notified instantly through multiple channels — Email, Discord, or Slack.",
  "",
  "### Notification Channels",
  "",
  "- **Email**: Direct delivery to your inbox with the failure reason and monitor name.",
  "- **Discord**: Real-time alerts sent to any Discord channel via a Webhook URL.",
  "- **Slack**: Clean, actionable alerts posted to any Slack channel via an Incoming Webhook.",
  "",
  "### Smart Alerting",
  "",
  "To prevent \"Alert Fatigue\", PingMyDB follows a strictly enforced cooldown logic:",
  "1. **Threshold**: Alerts only fire after a monitor fails **3 consecutive times**.",
  "2. **Cooldown**: After an alert is sent, a **30-minute cooldown** begins to prevent notification spam.",
  "3. **Recovery**: When a monitor comes back online, a recovery notification is sent immediately, resetting the cycle.",
  "",
  "---",
  "",
  "## 5a. Setting Up Discord Alerts",
  "",
  "PingMyDB can send real-time alerts directly to any Discord channel. Here's how to set it up from scratch.",
  "",
  "### Step 1 — Create or Open a Discord Server",
  "",
  "If you don't have a Discord account, sign up at [discord.com](https://discord.com). Once logged in:",
  "- Click the **+** button on the left sidebar to **Create a Server**.",
  "- Choose **Create My Own**, give it a name (e.g. `OpsAlerts`) and click **Create**.",
  "",
  "If you already have a server, open it and pick the channel you want alerts in — or create a dedicated `#db-alerts` channel.",
  "",
  "### Step 2 — Open Channel Settings",
  "",
  "- Hover over the target channel in the left sidebar.",
  "- Click the **⚙️ gear icon** to open **Channel Settings**.",
  "",
  "### Step 3 — Go to Integrations → Webhooks",
  "",
  "- In the channel settings sidebar, click **Integrations**.",
  "- Click **View Webhooks**, then **New Webhook**.",
  "- Give it a name like `PingMyDB Alerts` and optionally set an avatar.",
  "",
  "### Step 4 — Copy the Webhook URL",
  "",
  "- Click **Copy Webhook URL**. It will look like:",
  "```",
  "https://discord.com/api/webhooks/1234567890/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "```",
  "",
  "### Step 5 — Add it to PingMyDB",
  "",
  "- Go to **Dashboard → Settings → Notifications** tab.",
  "- Click **Add Channel**, select **Discord**.",
  "- Give it a name (e.g. `Production Discord`) and paste the Webhook URL.",
  "- Click **Create** and then **Send Test** to verify it works.",
  "",
  "> [!NOTE]",
  "> You'll receive a test message in your Discord channel immediately after hitting **Send Test**. If you don't see it, double-check the Webhook URL and make sure the channel hasn't been deleted.",
  "",
  "---",
  "",
  "## 5b. Setting Up Slack Alerts",
  "",
  "PingMyDB integrates with Slack via Incoming Webhooks. Here's the full setup guide.",
  "",
  "### Step 1 — Create or Open a Slack Workspace",
  "",
  "If you don't have Slack, sign up at [slack.com](https://slack.com). Once logged in:",
  "- Open or create a workspace where you want database alerts delivered.",
  "- Create a dedicated channel for alerts, e.g. `#db-monitoring`.",
  "",
  "### Step 2 — Create a Slack App",
  "",
  "- Visit [api.slack.com/apps/new](https://api.slack.com/apps/new).",
  "- Choose **From Scratch**.",
  "- Enter an App Name like `PingMyDB Alerts`.",
  "- Select your Workspace from the dropdown and click **Create App**.",
  "",
  "### Step 3 — Enable Incoming Webhooks",
  "",
  "- In your new Slack App settings, click **Incoming Webhooks** in the left sidebar.",
  "- Toggle the **Activate Incoming Webhooks** switch to **On**.",
  "",
  "### Step 4 — Add a Webhook to a Channel",
  "",
  "- Scroll down and click **Add New Webhook to Workspace**.",
  "- Select the channel where alerts should appear (e.g. `#db-monitoring`).",
  "- Click **Allow**.",
  "",
  "### Step 5 — Copy the Webhook URL",
  "",
  "- Your Webhook URL is now shown in the **Webhook URLs for Your Workspace** section. It looks like:",
  "```",
  "https://hooks.slack.com/services/YOUR_WORKSPACE/YOUR_CHANNEL/YOUR_TOKEN",
  "```",
  "",
  "### Step 6 — Add it to PingMyDB",
  "",
  "- Go to **Dashboard → Settings → Notifications** tab.",
  "- Click **Add Channel**, select **Slack**.",
  "- Give it a name (e.g. `Ops Slack`) and paste the Webhook URL.",
  "- Click **Create** and then **Send Test** to confirm it's working.",
  "",
  "> [!NOTE]",
  "> A `Hello from PingMyDB!` test message will appear in your Slack channel. If it doesn't show up, make sure the Webhook URL is correct and the bot has permission to post in that channel.",
  "",
  "---",
  "",
  "## 6. Verification Process",
  "",
  "Before saving a monitor, we strongly recommend using the **Verify** feature. This ensures that our workers can successfully reach your database.",
  "",
  "**What we check during verification:**",
  "",
  "1. **Host Reachability**: We verify that the hostname resolves and the port is open.",
  "2. **Protocol Handshake**: We ensure the database engine responds to the specific driver.",
  "3. **Authentication**: We validate that the credentials provided have sufficient permissions to connect.",
  "",
  "> [!IMPORTANT]",
  "> The most common cause of verification failure is a firewall block. Ensure your database provider allows connections from cloud worker IPs or set your network access to `0.0.0.0/0` temporarily to test.",
  "",
  "---",
  "",
  "## 7. Infrastructure Security",
  "",
  "Your database credentials are your most sensitive assets. We treat them with the highest level of security.",
  "",
  "**AES-256-GCM Encryption**",
  "",
  "Every URI is encrypted at the application layer before it ever touches our database. We use industry-standard GCM mode to ensure both data confidentiality and integrity.",
  "",
  "**Zero Log Policy**",
  "",
  "We never log connection strings, passwords, or query results. Our internal logs only track the success or failure status of the monitoring tasks.",
  "",
  "---",
  "",
  "## 8. Billing & Plans",
  "",
  "PingMyDB offers scales that grow with your infrastructure requirements.",
  "",
  "**Upgrading to Pro**",
  "",
  "You can upgrade your account instantly via our integrated **Razorpay** checkout. Pro accounts unlock:",
  "- **Higher Monitor Limits**: Scale up to 50 active monitors.",
  "- **Granular Intervals**: Ping intervals down to 1 minute.",
  "- **Priority Workers**: Faster processing in our distributed cluster.",
  "",
  "Payments are processed securely, and a confirmation email with your transaction ID is sent immediately upon success.",
  "",
  "---",
  "",
  "## 9. Common FAQ",
  "",
  "**Will this affect my database performance?**",
  "",
  "No. The resource footprint of a PingMyDB pulse is virtually zero. It is less than 0.1% of a standard t3.micro instance capacity.",
  "",
  "**Do you read my actual data?**",
  "",
  "Never. Our workers are hardcoded to only run no-op checks (`SELECT 1` or `admin.ping()`). We do not have the logic to perform `SELECT` statements on your application tables.",
  "",
  "**Can I monitor databases behind a VPC?**",
  "",
  "Currently, our workers require public internet access to reach your host. We are exploring SSH Tunneling and Site-to-Site VPN options for future updates.",
  "",
  "---",
  "",
  "## 11. Developer API & CLI",
  "",
  "PingMyDB is built for developers. You can interact with your monitoring data programmatically via our REST API or the official CLI tool.",
  "",
  "### API Keys",
  "",
  "Generate keys in the **Developer API** section of your dashboard. We use SHA-256 hashing to secure your keys—ensure you save the raw key immediately as it will only be shown once.",
  "",
  "**Authentication Header**",
  "| Header | Value |",
  "| :--- | :--- |",
  "| `x-api-key` | `pmdb_live_...` |",
  "",
  "### CLI Tool",
  "",
  "Monitor your infrastructure directly from your terminal. Our lightweight CLI supports login, status overview, and detailed health checks.",
  "",
  "```bash",
  "# Installation",
  "curl -sSL https://pingmydb.com/install.sh | bash",
  "",
  "# Usage",
  "pmdb login <your-api-key>",
  "pmdb status",
  "pmdb check <monitor-id>",
  "```",
  "",
  "---",
  "",
  "## 12. Future Roadmap",
  "",
  "We are constantly iterating on new ways to make database monitoring easier and more powerful.",
  "",
  "**Upcoming Features:**",
  "",
  "- **Multi-Region Pings**: Monitor your database from 5 different global locations simultaneously.",
  "- **Custom SQL Commands**: Define your own custom health checks and validation queries.",
  "- **Anomaly Detection**: Use ML to detect unusual latency patterns before they become failures.",
  "- **Team Workspaces**: Collaborate with your engineering team on shared infrastructure monitoring.",
  "",
  "---"
].join('\n');
